pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                
                echo 'build stage'
                git 'https://github.com/anushrishinde6/genzeonDemoDomParser.git'
            }
        }
    
     stage('test') {
            
            steps {
                echo 'test stage'
                
                  withAnt(installation: 'C:\\Users\\AShinde\\Downloads\\Apache-Ant\\apache-ant-1.10.6\\bin') {
    			   dir(".") {
    				if (isUnix()) {
      		         sh "ant mytarget"
    			    } else {
      			     bat "ant main"
      				}
    			}
         	}
     	}
  	}
        
    stage('deployment') {
            
            steps {
                echo 'deployment stage'
            }
        } 
     }
 }   