pipeline {
    agent any
    stages {
        stage('build') {
            /*steps {
                
                echo 'build stage'
                git 'https://github.com/anushrishinde6/genzeonDemoDomParser.git'
            }*/
            
            
            parallel
             {
                  stage('Test On Windows') {
                    steps {
                        
                    
             	    	
             	    		
                				bat "cd C:\\Users\\AShinde\\Desktop"
            					bat "abc.cmd"
            					sleep 1000
               	      	   
                         
                         
                            echo 'finally block'
                         
              }    
         }
        
       }     
       
 }
    
     stage('test') {
            
            steps {
                echo 'test stage'
                script 
                {
                  
    			   dir("C:\\Users\\AShinde\\git\\genzeonDemoDomParser\\com.genzeon.demo.domparser") {
    			
    		     	if (isUnix()) {
      		         sh "ant main"
    			    } else {
      			     bat "ant main"
      				}
    			}
    		}
        
        script 
                {
                  
    			   dir("C:\\Users\\AShinde\\Desktop") {
    			
    		     	if (isUnix()) {
      		         sh "ant main"
    			    } else {
      			     bat "abc.cmd"
      				}
    			}
    		} 
     }
  }
        
    stage('deployment') {
            
            steps {
                echo 'deployment stage'
            }
        } 
     }
 }   